version: "2.2"
services:
  arenah_postgres:
    image: "postgres:latest"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: arenah_development
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
volumes:
  data03:
    driver: local
