version: 2
jobs:
  build:
    working_directory: ~/arenah-rails
    docker:
      - image: cimg/ruby:2.5.0
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9
        environment:
        - POSTGRES_USER: postgres
        - POSTGRES_PASSWORD:
    steps:
      - checkout

      - run: BUNDLER_VERSION=$(awk '/BUNDLED WITH/ { getline; print $1 }' Gemfile.lock) && gem install --no-document bundler -v $BUNDLER_VERSION

      - restore_cache:
          key: arenah-rails-{{ .Branch }}{{ checksum "Gemfile.lock" }}

      - run:
          name: Set platform to linux
          command: |
            bundle lock --add-platform x86_64-linux

      - run:
          name: Install Bundler dependencies
          command: |
            bundle install --without development \
                           --deployment \
                           --retry=3 \
                           --jobs=3

      - save_cache:
          key: arenah-rails-{{ .Branch }}{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: cp .env.example .env
      - run: cp config/database.ymlsample config/database.yml

      - run: bundle exec rake db:create db:schema:load

      - run: bundle exec rake assets:precompile

      - run: |
          bundle exec rspec --profile 10 \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - store_test_results:
          path: /tmp/test_results
