default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRESQL_USER"] || ENV["USER"] || "postgres" %>
  database: <%= ENV["POSTGRESQL_DATABASE"] || "arenah_development" %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  host: <%= ENV["POSTGRESQL_HOST"] || "localhost" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5432 %>

development:
  <<: *default
  database: arenah_development

test:
  <<: *default
  database: arenah_test

production:
  <<: *default
  database: arenah_production
